services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://flashmaster:unknown@postgres/flashmasters_backend
  postgres:
    image: postgres:9.6.2-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER:      flashmaster
      POSTGRES_DB:        flashmasters_backend
      POSTGRES_PASSWORD:  unknown